name: Build Barry_PayWiFi Flutter App for ALL Platforms

on:
  workflow_dispatch:

jobs:

  Build-Android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_flutter

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app_flutter/build/app/outputs/flutter-apk/app-release.apk

  Build-Web-Linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_flutter

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Build Linux
        run: flutter build linux

      - name: Upload Web & Linux Builds
        uses: actions/upload-artifact@v4
        with:
          name: web-linux-builds
          path: |
            app_flutter/build/web
            app_flutter/build/linux
