name: Build Barry_PayWIFI Flutter App for ALL Platforms

on:
  workflow_dispatch:

jobs:

  Build-Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set Flutter Project Directory
        run: cd app_flutter
      - name: Install dependencies
        working-directory: ./app_flutter
        run: flutter pub get
      - name: Build APK
        working-directory: ./app_flutter
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: app_flutter/build/app/outputs/flutter-apk/app-release.apk

  Build-Web-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        working-directory: ./app_flutter
        run: flutter pub get
      - name: Build Web
        working-directory: ./app_flutter
        run: flutter build web
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: Web-Build
          path: app_flutter/build/web

      - name: Build Linux
        working-directory: ./app_flutter
        run: flutter build linux
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Build
          path: app_flutter/build/linux/x64/release/bundle
